name: MelonGems
version: '${project.version}'
main: dev.gir0fa.melongems.PowerGems
api-version: '1.19'
author: Gir0fa
load: STARTUP
softdepend: [WorldGuard]
commands:
  getallgems:
    description: Command to give yourself all gems
    usage: /getallgems
    permission: melongems.getallgems
  givegem:
    description: Command to give yourself a gem
    usage: /givegem <gem>
    permission: melongems.givegem
  giveallgem:
    description: Command to give everyone a gem
    usage: /giveallgem <gem>
    permission: melongems.giveallgem
  checkupdates:
    description: Command to check for updates
    usage: /checkupdates
    permission: melongems.checkupdates
  reloadconfig:
    description: Command to reload the config files
    usage: /reloadconfig
    aliases: [rc]
    permission: melongems.reloadconfig
  pgDebug:
    description: Debug command
    usage: /pgDebug
    aliases: [pgd, pgdb]
    permission: melongems.debug
permissions:
    melongems.getallgems:
        description: Permission to use /getallgem
        default: op
    melongems.givegem:
        description: Permission to use /givegem
        default: op
    melongems.giveallgem:
        description: Permission to use /giveallgem
        default: op
    melongems.checkupdates:
        description: Permission to use /checkupdates
        default: op
    melongems.reloadconfig:
        description: Permission to use /reloadconfig
        default: op
    melongems.debug:
        description: Permission to use /debug
        default: op
    melongems.*:
        description: Permission to use all melongems commands
        default: op
        children:
            melongems.getallgems: true
            melongems.givegem: true
            melongems.giveallgem: true
            melongems.checkupdates: true
            melongems.reloadconfig: true
            melongems.debug: true
